-- Initial schema. Safe to apply on an empty database.

DO $$ BEGIN
  CREATE TYPE job_execution_status AS ENUM (
    'PENDING', 'QUEUE', 'EXECUTING', 'COMPLETED', 'FAILED', 'REJECT', 'CANCELLED', 'SQUARED_OFF'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE day_of_week_enum AS ENUM (
    'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE chase_status_type AS ENUM (
    'SHORT', 'LONG', 'AWAITING_SHORT', 'AWAITING_LONG', 'AWAITING_SIGNAL'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE job_execution_strategy AS ENUM (
    'ATM_STRADDLE', 'ATM_STRANGLE', 'SUBSCRIBE_CHASE'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS trade_plans (
  id text PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  strategy job_execution_strategy NOT NULL,
  instrument text NOT NULL,
  expiry_type text NOT NULL,
  product_type text NOT NULL,
  day_of_week day_of_week_enum,
  exit_strategy text,
  combined_exit_strategy text,
  run_at timestamptz,
  square_off_time timestamptz,
  expires_at timestamptz,
  expire_if_unsuccessful_in_mins integer,
  lots integer NOT NULL,
  slm_percent smallint,
  sl_order_type text,
  sl_limit_price_percent smallint,
  max_profit_points smallint,
  is_max_profit_enabled boolean DEFAULT false,
  max_loss_points smallint,
  is_max_loss_enabled boolean DEFAULT false,
  threshold_skew_percent smallint,
  max_skew_percent smallint,
  take_trade_irrespective_skew boolean DEFAULT false,
  volatility_type text,
  trail_every_percentage_change_value smallint,
  trailing_sl_percent smallint,
  trailing_max_profit_points smallint,
  trailing_max_loss_points smallint,
  trailing_profit_percent numeric,
  is_auto_square_off_enabled boolean DEFAULT false,
  auto_square_off_time timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS job_executions (
  id text PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  name text,
  status job_execution_status,
  instrument text,
  strategy job_execution_strategy,
  exit_strategy text,
  combined_exit_strategy text,
  expiry_type text,
  product_type text,
  volatility_type text,
  sl_order_type text,
  order_tag text,
  lots smallint,
  slm_percent numeric,
  sl_limit_price_percent numeric,
  max_profit_points numeric,
  max_loss_points numeric,
  current_points numeric,
  trailing_sl_percent numeric,
  trailing_max_profit_points numeric,
  trailing_max_loss_points numeric,
  trailing_profit_percent numeric,
  trail_every_pct_change_value numeric,
  threshold_skew_percent numeric,
  max_skew_percent numeric,
  expire_if_unsuccessful_in_mins smallint,
  is_max_profit_enabled boolean DEFAULT false,
  is_max_loss_enabled boolean DEFAULT false,
  is_auto_square_off_enabled boolean DEFAULT false,
  take_trade_irrespective_skew boolean DEFAULT false,
  on_square_off_set_aborted boolean DEFAULT false,
  run_now boolean DEFAULT false,
  square_off_time timestamptz,
  expires_at timestamptz,
  run_at timestamptz,
  last_target_at timestamptz,
  last_modified timestamptz,
  auto_square_off_props jsonb,
  queue jsonb,
  auto_square_off_time timestamptz,
  auto_square_off_delete_pending_orders boolean DEFAULT false,
  day_of_week day_of_week_enum,
  trail_every_percentage_change_value smallint,
  plan_ref text REFERENCES trade_plans(id),
  user_override text,
  live_trailing_sl numeric,
  last_trailing_sl_set_at timestamptz,
  last_heartbeat_at timestamptz,
  updated_at timestamptz
);

CREATE TABLE IF NOT EXISTS ema (
  id serial PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  tradingsymbol text NOT NULL,
  ema integer,
  instrument_token integer,
  highest_high integer,
  lowest_low integer,
  last_close integer
);

CREATE TABLE IF NOT EXISTS chase_status (
  id serial PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  last_modified_at timestamptz DEFAULT now(),
  current_status chase_status_type,
  tradingsymbol text,
  instrument_token integer,
  stoploss integer,
  entry_point integer,
  is_signal_breaching_tolerance boolean
);

CREATE TABLE IF NOT EXISTS chase_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL,
  tradingsymbol text NOT NULL,
  transaction_type text NOT NULL,
  average_price numeric
);

CREATE TABLE IF NOT EXISTS accesstoken (
  id serial PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  access_token text NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions (
  id serial PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  order_timestamp timestamptz,
  exchange text,
  tradingsymbol text,
  instrument_token integer,
  transaction_type text,
  quantity integer,
  average_price numeric,
  tag text,
  order_id text,
  variety text,
  order_type text,
  product text
);

CREATE INDEX IF NOT EXISTS idx_trade_plans_created_at ON trade_plans (created_at);
CREATE INDEX IF NOT EXISTS idx_trade_plans_instrument ON trade_plans (instrument);
CREATE INDEX IF NOT EXISTS idx_trade_plans_strategy ON trade_plans (strategy);
