-- Trading ledger: orders, fills, positions, trades, portfolio, audit.
-- Existing job_executions / transactions / chase tables are unchanged.

CREATE TABLE IF NOT EXISTS trading_accounts (
  id text PRIMARY KEY DEFAULT 'default',
  broker text NOT NULL DEFAULT 'ZERODHA',
  broker_user_id text,
  display_name text,
  currency text NOT NULL DEFAULT 'INR',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO trading_accounts (id, display_name)
VALUES ('default', 'Zerodha Kite')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS trading_decisions (
  id text PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id text NOT NULL REFERENCES trading_accounts(id),
  job_id text REFERENCES job_executions(id) ON DELETE SET NULL,
  strategy text,
  instrument text,
  tradingsymbol text,
  exchange text,
  side text,
  action text NOT NULL,
  intent text,
  reason text,
  risk_result text,
  risk_detail text,
  parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
  features jsonb NOT NULL DEFAULT '{}'::jsonb,
  current_position_qty integer,
  proposed_qty integer,
  proposed_price numeric(18, 4),
  order_id text,
  idempotency_key text NOT NULL,
  occurred_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  provenance text NOT NULL DEFAULT 'LIVE',
  CONSTRAINT trading_decisions_action_chk CHECK (action IN ('ENTER', 'EXIT', 'HOLD', 'SKIP', 'ADJUST_SL', 'RISK_BLOCK')),
  CONSTRAINT trading_decisions_risk_chk CHECK (risk_result IS NULL OR risk_result IN ('PASSED', 'FAILED', 'SKIPPED')),
  CONSTRAINT trading_decisions_side_chk CHECK (side IS NULL OR side IN ('BUY', 'SELL')),
  CONSTRAINT trading_decisions_provenance_chk CHECK (provenance IN ('LIVE', 'MIGRATED', 'RECONCILED', 'MOCK'))
);

CREATE UNIQUE INDEX IF NOT EXISTS trading_decisions_idempotency_uidx ON trading_decisions (idempotency_key);
CREATE INDEX IF NOT EXISTS idx_trading_decisions_job ON trading_decisions (job_id);
CREATE INDEX IF NOT EXISTS idx_trading_decisions_occurred ON trading_decisions (occurred_at);

CREATE TABLE IF NOT EXISTS orders (
  id text PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id text NOT NULL REFERENCES trading_accounts(id),
  job_id text REFERENCES job_executions(id) ON DELETE SET NULL,
  decision_id text REFERENCES trading_decisions(id) ON DELETE SET NULL,
  strategy text,
  order_tag text,
  purpose text NOT NULL DEFAULT 'OTHER',
  side text NOT NULL,
  order_type text,
  product text,
  exchange text NOT NULL,
  tradingsymbol text NOT NULL,
  instrument_token integer,
  validity text,
  time_in_force text,
  requested_qty integer NOT NULL,
  filled_qty integer NOT NULL DEFAULT 0,
  remaining_qty integer NOT NULL,
  limit_price numeric(18, 4),
  stop_price numeric(18, 4),
  average_fill_price numeric(18, 4),
  fees numeric(18, 4) NOT NULL DEFAULT 0,
  status text NOT NULL,
  broker_order_id text,
  exchange_order_id text,
  parent_broker_order_id text,
  idempotency_key text NOT NULL,
  reject_reason text,
  cancel_reason text,
  error_info text,
  broker_status text,
  raw_broker jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  provenance text NOT NULL DEFAULT 'LIVE',
  submitted_at timestamptz,
  accepted_at timestamptz,
  filled_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT orders_side_chk CHECK (side IN ('BUY', 'SELL')),
  CONSTRAINT orders_purpose_chk CHECK (purpose IN ('ENTRY', 'EXIT', 'HEDGE', 'SL', 'SQUARE_OFF', 'OTHER')),
  CONSTRAINT orders_status_chk CHECK (status IN (
    'PENDING', 'SUBMITTED', 'ACCEPTED', 'PARTIALLY_FILLED', 'FILLED',
    'CANCEL_REQUESTED', 'CANCELLED', 'REJECTED', 'EXPIRED', 'FAILED', 'UNKNOWN'
  )),
  CONSTRAINT orders_qty_chk CHECK (requested_qty > 0 AND filled_qty >= 0 AND remaining_qty >= 0 AND filled_qty <= requested_qty),
  CONSTRAINT orders_provenance_chk CHECK (provenance IN ('LIVE', 'MIGRATED', 'RECONCILED', 'MOCK'))
);

CREATE UNIQUE INDEX IF NOT EXISTS orders_idempotency_uidx ON orders (idempotency_key);
CREATE UNIQUE INDEX IF NOT EXISTS orders_broker_order_id_uidx ON orders (broker_order_id) WHERE broker_order_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_orders_job ON orders (job_id);
CREATE INDEX IF NOT EXISTS idx_orders_tag ON orders (order_tag);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_symbol ON orders (exchange, tradingsymbol, product);

CREATE TABLE IF NOT EXISTS order_events (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_id text NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  from_status text,
  to_status text NOT NULL,
  event_type text NOT NULL,
  broker_status text,
  filled_qty integer,
  remaining_qty integer,
  message text,
  raw jsonb,
  occurred_at timestamptz NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_order_events_order ON order_events (order_id, recorded_at);

CREATE TABLE IF NOT EXISTS fills (
  id text PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id text NOT NULL REFERENCES trading_accounts(id),
  order_id text NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  job_id text REFERENCES job_executions(id) ON DELETE SET NULL,
  decision_id text REFERENCES trading_decisions(id) ON DELETE SET NULL,
  strategy text,
  broker_order_id text,
  broker_trade_id text,
  exchange text NOT NULL,
  tradingsymbol text NOT NULL,
  instrument_token integer,
  product text,
  side text NOT NULL,
  quantity integer NOT NULL,
  price numeric(18, 4) NOT NULL,
  fee_amount numeric(18, 4) NOT NULL DEFAULT 0,
  fee_currency text NOT NULL DEFAULT 'INR',
  liquidity text,
  fingerprint text NOT NULL,
  occurred_at timestamptz NOT NULL,
  broker_time timestamptz,
  recorded_at timestamptz NOT NULL DEFAULT now(),
  applied_at timestamptz,
  raw_broker jsonb,
  provenance text NOT NULL DEFAULT 'LIVE',
  CONSTRAINT fills_side_chk CHECK (side IN ('BUY', 'SELL')),
  CONSTRAINT fills_qty_chk CHECK (quantity > 0),
  CONSTRAINT fills_provenance_chk CHECK (provenance IN ('LIVE', 'MIGRATED', 'RECONCILED', 'MOCK'))
);

CREATE UNIQUE INDEX IF NOT EXISTS fills_fingerprint_uidx ON fills (fingerprint);
CREATE UNIQUE INDEX IF NOT EXISTS fills_broker_trade_id_uidx ON fills (broker_trade_id) WHERE broker_trade_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_fills_order ON fills (order_id);
CREATE INDEX IF NOT EXISTS idx_fills_unapplied ON fills (applied_at) WHERE applied_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_fills_symbol ON fills (exchange, tradingsymbol, occurred_at);

CREATE TABLE IF NOT EXISTS positions (
  id text PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id text NOT NULL REFERENCES trading_accounts(id),
  job_id text REFERENCES job_executions(id) ON DELETE SET NULL,
  strategy text,
  exchange text NOT NULL,
  tradingsymbol text NOT NULL,
  instrument_token integer,
  product text NOT NULL DEFAULT '',
  quantity integer NOT NULL DEFAULT 0,
  average_entry_price numeric(18, 4) NOT NULL DEFAULT 0,
  cost_basis numeric(18, 4) NOT NULL DEFAULT 0,
  realized_pnl numeric(18, 4) NOT NULL DEFAULT 0,
  fees numeric(18, 4) NOT NULL DEFAULT 0,
  mark_price numeric(18, 4),
  unrealized_pnl numeric(18, 4),
  market_value numeric(18, 4),
  opened_at timestamptz,
  closed_at timestamptz,
  last_fill_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'FLAT',
  CONSTRAINT positions_status_chk CHECK (status IN ('OPEN', 'FLAT'))
);

CREATE UNIQUE INDEX IF NOT EXISTS positions_book_uidx
  ON positions (account_id, exchange, tradingsymbol, product, COALESCE(job_id, ''));
CREATE INDEX IF NOT EXISTS idx_positions_open ON positions (status) WHERE status = 'OPEN';

CREATE TABLE IF NOT EXISTS position_events (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  position_id text NOT NULL REFERENCES positions(id) ON DELETE CASCADE,
  fill_id text REFERENCES fills(id) ON DELETE SET NULL,
  event_kind text NOT NULL,
  quantity_before integer,
  quantity_after integer,
  average_before numeric(18, 4),
  average_after numeric(18, 4),
  realized_delta numeric(18, 4),
  fee_delta numeric(18, 4),
  mark_price numeric(18, 4),
  reason text,
  occurred_at timestamptz NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT position_events_kind_chk CHECK (event_kind IN ('OPENED', 'INCREASED', 'REDUCED', 'CLOSED', 'REVERSED', 'MARKED'))
);

CREATE INDEX IF NOT EXISTS idx_position_events_position ON position_events (position_id, recorded_at);

CREATE TABLE IF NOT EXISTS trades (
  id text PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id text NOT NULL REFERENCES trading_accounts(id),
  job_id text REFERENCES job_executions(id) ON DELETE SET NULL,
  decision_id text REFERENCES trading_decisions(id) ON DELETE SET NULL,
  exit_decision_id text REFERENCES trading_decisions(id) ON DELETE SET NULL,
  position_id text REFERENCES positions(id) ON DELETE SET NULL,
  strategy text,
  exchange text NOT NULL,
  tradingsymbol text NOT NULL,
  product text NOT NULL DEFAULT '',
  direction text NOT NULL,
  status text NOT NULL,
  entry_qty integer NOT NULL DEFAULT 0,
  exit_qty integer NOT NULL DEFAULT 0,
  average_entry numeric(18, 4) NOT NULL DEFAULT 0,
  average_exit numeric(18, 4),
  gross_pnl numeric(18, 4) NOT NULL DEFAULT 0,
  fees numeric(18, 4) NOT NULL DEFAULT 0,
  net_pnl numeric(18, 4) NOT NULL DEFAULT 0,
  return_pct numeric(18, 6),
  holding_period_ms bigint,
  mfe numeric(18, 4),
  mae numeric(18, 4),
  entry_at timestamptz NOT NULL,
  exit_at timestamptz,
  exit_reason text,
  provenance text NOT NULL DEFAULT 'LIVE',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT trades_direction_chk CHECK (direction IN ('LONG', 'SHORT')),
  CONSTRAINT trades_status_chk CHECK (status IN ('OPEN', 'CLOSED')),
  CONSTRAINT trades_exit_reason_chk CHECK (
    exit_reason IS NULL OR exit_reason IN (
      'STRATEGY', 'STOP_LOSS', 'TAKE_PROFIT', 'TRAILING_STOP', 'RISK_LIMIT',
      'MAX_HOLDING', 'MANUAL', 'SHUTDOWN', 'BROKER', 'ROLLBACK', 'RECONCILED',
      'MIGRATED', 'UNKNOWN'
    )
  )
);

CREATE INDEX IF NOT EXISTS idx_trades_status ON trades (status);
CREATE INDEX IF NOT EXISTS idx_trades_job ON trades (job_id);
CREATE INDEX IF NOT EXISTS idx_trades_entry ON trades (entry_at);
CREATE UNIQUE INDEX IF NOT EXISTS trades_open_position_uidx ON trades (position_id) WHERE status = 'OPEN';

CREATE TABLE IF NOT EXISTS fees (
  id text PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id text NOT NULL REFERENCES trading_accounts(id),
  order_id text REFERENCES orders(id) ON DELETE SET NULL,
  fill_id text REFERENCES fills(id) ON DELETE SET NULL,
  trade_id text REFERENCES trades(id) ON DELETE SET NULL,
  amount numeric(18, 4) NOT NULL,
  currency text NOT NULL DEFAULT 'INR',
  fee_type text NOT NULL,
  broker text,
  occurred_at timestamptz NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT now(),
  notes text,
  provenance text NOT NULL DEFAULT 'LIVE',
  CONSTRAINT fees_type_chk CHECK (fee_type IN ('BROKERAGE', 'EXCHANGE', 'STT', 'GST', 'STAMP', 'OTHER'))
);

CREATE INDEX IF NOT EXISTS idx_fees_order ON fees (order_id);

CREATE TABLE IF NOT EXISTS portfolio_snapshots (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  account_id text NOT NULL REFERENCES trading_accounts(id),
  session_date date NOT NULL,
  captured_at timestamptz NOT NULL DEFAULT now(),
  source text NOT NULL,
  available_cash numeric(18, 4),
  used_margin numeric(18, 4),
  span numeric(18, 4),
  exposure numeric(18, 4),
  gross_exposure numeric(18, 4),
  net_exposure numeric(18, 4),
  realized_pnl numeric(18, 4),
  unrealized_pnl numeric(18, 4),
  fees numeric(18, 4),
  portfolio_value numeric(18, 4),
  peak_equity numeric(18, 4),
  drawdown numeric(18, 4),
  drawdown_pct numeric(18, 6),
  open_position_count integer,
  raw_margins jsonb,
  notes text
);

CREATE INDEX IF NOT EXISTS idx_portfolio_snapshots_session ON portfolio_snapshots (account_id, session_date, captured_at);

CREATE TABLE IF NOT EXISTS daily_sessions (
  account_id text NOT NULL REFERENCES trading_accounts(id),
  session_date date NOT NULL,
  starting_equity numeric(18, 4),
  ending_equity numeric(18, 4),
  peak_equity numeric(18, 4),
  max_drawdown numeric(18, 4),
  realized_pnl numeric(18, 4) NOT NULL DEFAULT 0,
  unrealized_pnl numeric(18, 4) NOT NULL DEFAULT 0,
  fees numeric(18, 4) NOT NULL DEFAULT 0,
  gross_pnl numeric(18, 4) NOT NULL DEFAULT 0,
  net_pnl numeric(18, 4) NOT NULL DEFAULT 0,
  order_count integer NOT NULL DEFAULT 0,
  fill_count integer NOT NULL DEFAULT 0,
  trade_count integer NOT NULL DEFAULT 0,
  win_count integer NOT NULL DEFAULT 0,
  loss_count integer NOT NULL DEFAULT 0,
  largest_win numeric(18, 4),
  largest_loss numeric(18, 4),
  avg_win numeric(18, 4),
  avg_loss numeric(18, 4),
  win_rate numeric(18, 6),
  exposure_peak numeric(18, 4),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (account_id, session_date)
);

CREATE TABLE IF NOT EXISTS reconciliation_events (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  account_id text NOT NULL REFERENCES trading_accounts(id),
  kind text NOT NULL,
  severity text NOT NULL DEFAULT 'WARN',
  instrument text,
  tradingsymbol text,
  exchange text,
  product text,
  internal_qty integer,
  broker_qty integer,
  internal_avg numeric(18, 4),
  broker_avg numeric(18, 4),
  internal_order_id text,
  broker_order_id text,
  detail text,
  resolved boolean NOT NULL DEFAULT false,
  resolved_at timestamptz,
  resolved_how text,
  raw jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  recorded_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT recon_kind_chk CHECK (kind IN (
    'POSITION_MISMATCH', 'AVG_PRICE', 'MISSING_ORDER', 'UNEXPECTED_ORDER',
    'FILL_MISMATCH', 'STALE_PENDING', 'UNKNOWN_BROKER_ORDER'
  ))
);

CREATE INDEX IF NOT EXISTS idx_recon_unresolved ON reconciliation_events (resolved, occurred_at DESC);

CREATE TABLE IF NOT EXISTS audit_events (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  account_id text NOT NULL REFERENCES trading_accounts(id),
  job_id text REFERENCES job_executions(id) ON DELETE SET NULL,
  order_id text REFERENCES orders(id) ON DELETE SET NULL,
  decision_id text REFERENCES trading_decisions(id) ON DELETE SET NULL,
  position_id text REFERENCES positions(id) ON DELETE SET NULL,
  trade_id text REFERENCES trades(id) ON DELETE SET NULL,
  event_type text NOT NULL,
  severity text NOT NULL DEFAULT 'INFO',
  actor text NOT NULL DEFAULT 'SYSTEM',
  summary text,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  idempotency_key text,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  recorded_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS audit_events_idempotency_uidx
  ON audit_events (event_type, idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_audit_events_occurred ON audit_events (occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_type ON audit_events (event_type);
