-- Persisted strategy evaluations (Chase EMA compare, skew wait, strike pick).
-- operator_feed_clears hides Alerts without deleting ledger/audit rows.

CREATE TABLE IF NOT EXISTS strategy_signals (
  id text PRIMARY KEY DEFAULT gen_random_uuid(),
  occurred_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  strategy text,
  instrument text,
  tradingsymbol text,
  job_id text REFERENCES job_executions(id) ON DELETE SET NULL,
  plan_ref text,
  order_tag text,
  job_name text,
  kind text NOT NULL,
  outcome text NOT NULL,
  summary text NOT NULL,
  features jsonb NOT NULL DEFAULT '{}'::jsonb,
  idempotency_key text NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS strategy_signals_idempotency_uidx
  ON strategy_signals (idempotency_key);
CREATE INDEX IF NOT EXISTS idx_strategy_signals_occurred ON strategy_signals (occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_strategy_signals_strategy ON strategy_signals (strategy);
CREATE INDEX IF NOT EXISTS idx_strategy_signals_job ON strategy_signals (job_id);
CREATE INDEX IF NOT EXISTS idx_strategy_signals_plan ON strategy_signals (plan_ref);
CREATE INDEX IF NOT EXISTS idx_strategy_signals_tag ON strategy_signals (order_tag);

CREATE TABLE IF NOT EXISTS operator_feed_clears (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  feed text NOT NULL,
  mode text NOT NULL,
  ist_date date,
  before timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT operator_feed_clears_feed_chk CHECK (feed IN ('alerts', 'signals')),
  CONSTRAINT operator_feed_clears_mode_chk CHECK (mode IN ('all', 'today', 'before_today'))
);

CREATE INDEX IF NOT EXISTS idx_operator_feed_clears_feed ON operator_feed_clears (feed, created_at DESC);
